releasedate: "2023-05-20"
sage: "SageMath"
logo: "pix/logo_sagemath+icon_oldstyle.png"
version: "10.0"
version_solaris_bin: None
version_src: "10.0"
git: "https://github.com/sagemath/sage.git"
git_website: "https://github.com/sagemath/website"
webmaster_href: "mailto:harald+smo@schil.ly"

# the docroot is the base URL for the documentation.
# the directory structure is (more or less) the same as in SageMath's "output" directory in doc
docroot: "https://doc.sagemath.org"
