releasedate: "2022-09-19"
sage: "SageMath"
logo: "pix/logo_sagemath+icon_oldstyle.png"
version: "9.7"
version_solaris_bin: None
version_src: "9.7"
git: "https://git.sagemath.org/sage.git/"
git_website: "https://github.com/sagemath/website"
webmaster_href: "mailto:harald+smo@schil.ly"

# the docroot is the base URL for the documentation.
# the directory structure is (more or less) the same as in SageMath's "output" directory in doc
docroot: "https://doc.sagemath.org"
